name: user_articles
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  retrofit: ^3.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
